[package]
name = "rooibos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["sgx-tkeys"]

[dependencies]
sgx-tkeys = { path="./sgx-tkeys" }
